services:
  frontend:
    image: taskflow-frontend:staging
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "staging"
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
